workflows:
  ios-flutter-workflow:
    name: Build iOS App
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: CaptureProiOS
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS Application
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
